apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-hello-world
  labels:
    run: hello-world
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helloWorld.type }}
  selector:
    run: hello-world
  {{- include "hello-world.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.helloWorld.ports | toYaml | nindent 2 -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-world.fullname" . }}-hello-world
  labels:
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: arthur.nurigundogan.net
    http:
      paths:
      - backend:
          service:
            name: '{{ include "hello-world.fullname" . }}-hello-world'
            port:
              number: 80
        path: /
        pathType: Prefix