apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  labels:
    app: curator
data:
  action_file.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 30
          exclude: False
  config.yml: |-
    ---
    client:
      hosts:
        - elasticsearch
      port: 9200
      use_ssl: False
      ssl_no_validate: False
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curator
  labels:
    app: curator
spec:
  schedule: "0 22 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: bobrik/curator:5.8.1
            name: curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
            - name: config
              mountPath: /etc/config
          volumes:
          - name: config
            configMap:
              name: curator-config
          restartPolicy: OnFailure
